# PyTorch Basics

In this notebook, we will learn the PyTorch tools needed for simple deep learning.

You will practice:
- creating tensors
- changing tensor shape
- using basic tensor math
- loading image data
- batching data with a DataLoader
- building a tiny neural network
- running a forward pass
- computing loss
- training a model for a few steps

These ideas will prepare you for image classification tasks later.

## What is PyTorch?

PyTorch is a library for deep learning.

It gives us:
- tensors, which are like NumPy arrays
- automatic differentiation
- neural network layers
- training utilities

In [1]:
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader

## Tensors

A tensor is the main data type in PyTorch.

You can think of it as a NumPy-like array that works well with neural networks.

In [2]:
# Create a 1D tensor.

x = torch.tensor([1.0, 2.0, 3.0])
print(x)
print("shape:", x.shape)
print("dtype:", x.dtype)

tensor([1., 2., 3.])
shape: torch.Size([3])
dtype: torch.float32


In [3]:
# Create a 2D tensor.

A = torch.tensor([
    [1.0, 2.0],
    [3.0, 4.0]
])

print(A)
print("shape:", A.shape)

tensor([[1., 2.],
        [3., 4.]])
shape: torch.Size([2, 2])


## Basic tensor operations

Many tensor operations look similar to NumPy.

In [4]:
# Element-wise addition and multiplication.

print("A + A:\n", A + A)
print("A * A:\n", A * A)

A + A:
 tensor([[2., 4.],
        [6., 8.]])
A * A:
 tensor([[ 1.,  4.],
        [ 9., 16.]])


In [5]:
# Scalar operations.

print("A * 2:\n", A * 2)

A * 2:
 tensor([[2., 4.],
        [6., 8.]])


## Reshape and flatten

Neural networks often expect data in a specific shape.
PyTorch makes reshaping easy.

In [6]:
# Reshape a tensor.

B = torch.arange(12)
print("B:", B)
print("B reshaped:\n", B.reshape(3, 4))

B: tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
B reshaped:
 tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [7]:
# Flatten a tensor back into 1D.

C = torch.arange(12).reshape(3, 4)
print("Original shape:", C.shape)
print("Flattened shape:", C.flatten().shape)

Original shape: torch.Size([3, 4])
Flattened shape: torch.Size([12])


## Indexing tensors

Tensor indexing works like NumPy indexing.

In [8]:
# Access rows, columns, and single values.

print(C[0])
print(C[:, 1])
print(C[1, 2])

tensor([0, 1, 2, 3])
tensor([1, 5, 9])
tensor(6)


## Gradients

PyTorch can compute gradients automatically.
This is what makes training neural networks possible.

In [9]:
# Create a tensor that tracks gradients.

w = torch.tensor(2.0, requires_grad=True)
x = torch.tensor(3.0)

y = w * x
print("y:", y)

y: tensor(6., grad_fn=<MulBackward0>)


In [10]:
# Backpropagate through the computation graph.

y.backward()
print("gradient of w:", w.grad)

gradient of w: tensor(3.)


In [11]:
# Backpropagate through the computation graph.

y.backward()
print("gradient of w:", w.grad)

RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.

## Simple neural network layer

A linear layer is one of the simplest building blocks in deep learning.
It learns a weighted combination of input values.

In [ ]:
# A tiny linear layer with 4 inputs and 2 outputs.

layer = nn.Linear(4, 2)
print(layer)

In [ ]:
# Create one fake input example with 4 features.

x = torch.randn(1, 4)
output = layer(x)

print("input shape:", x.shape)
print("output shape:", output.shape)
print(output)

## Activation functions

Activation functions add nonlinearity to a model.
A common one is ReLU.

In [ ]:
relu = nn.ReLU()

values = torch.tensor([-2.0, -1.0, 0.0, 1.0, 2.0])
print(relu(values))

## Loss functions

A loss function measures how wrong the model is.

During training, we try to reduce the loss.

In [ ]:
# Example for a classification task with 2 classes.

loss_fn = nn.CrossEntropyLoss()

logits = torch.tensor([[2.0, 0.5],
                       [0.1, 1.7]])

labels = torch.tensor([0, 1])

loss = loss_fn(logits, labels)
print("loss:", loss.item())

## Optimizers

An optimizer updates model parameters using gradients.

In [ ]:
model = nn.Linear(4, 2)
optimizer = torch.optim.SGD(model.parameters(), lr=0.1)

## Tiny training step

Below is the standard pattern:
1. zero gradients
2. forward pass
3. compute loss
4. backward pass
5. update parameters

In [ ]:
x = torch.randn(5, 4)
y = torch.tensor([0, 1, 0, 1, 1])

logits = model(x)
loss = loss_fn(logits, y)

optimizer.zero_grad()
loss.backward()
optimizer.step()

print("loss:", loss.item())

## Dataset and DataLoader

A Dataset stores examples.

A DataLoader makes batches automatically.
This is very useful when training on many images.

In [ ]:
class ToyDataset(Dataset):
    def __init__(self):
        self.x = torch.randn(20, 4)
        self.y = torch.randint(0, 2, (20,))

    def __len__(self):
        return len(self.x)

    def __getitem__(self, idx):
        return self.x[idx], self.y[idx]

In [ ]:
dataset = ToyDataset()
loader = DataLoader(dataset, batch_size=4, shuffle=True)

for batch_x, batch_y in loader:
    print("batch_x shape:", batch_x.shape)
    print("batch_y shape:", batch_y.shape)
    break